### ISSUE TITLE
Long Description

### ISSUE THREAD

**Issue by navulirs** [felipeochoa/minecart#11]
Hi Installation pip install minecart produces this error - 'ascii' codec can't decode byte 0xe2 

it is pointing to the Long Description in the setup.py

OS - Ubuntu 16.04
Python version - 2.7.14 and 3.5.2

**Comment by felipeochoa** [comment]
I've been unable to reproduce this issue. Can you try again with Python 3? (Since v0.3, minecart is Py3 only). Here are the steps I followed to attempt to reproduce:

```sh
mkdir /tmp/minecart-test
cd /tmp/minecart-test
python3 -m venv test
. test/bin/activate
pip install minecart --no-cache-dir
python -c 'import minecart; print(minecart)'
```

**Comment by felipeochoa** [comment]
Housekeeping
