### ISSUE TITLE
What does lettering print

### ISSUE THREAD

**Issue by harsha-99** [felipeochoa/minecart#12]
what does string.lettering print could pls explain in detail i can only see a 4 tuple format beside a particular letter

**Comment by felipeochoa** [comment]
I don't understand your question. `Lettering` is a `str` subclass, that also has a `.get_bbox()` method returning the bounding box of the text in `(x1, y1, x2, y2)` format and a `.font` property

**Comment by harsha-99** [comment]
thanks for replying,i got the box boundary as four tuple but how do we get font information, i mean what is syntax of code to be used.

**Comment by felipeochoa** [comment]
The `.font` property has the font information. Unfortunately, there isn't much documentation on this, but you can see the `PDFFont` class that pdfminer uses [here](https://github.com/euske/pdfminer/blob/master/pdfminer/pdffont.py#L467)
