### ISSUE TITLE
Error in doc.get_page()

### ISSUE THREAD

**Issue by himansu979** [felipeochoa/minecart#15]
Hi, I am getting error in reading a specific page using doc.get_page(). Anything I need to change in this package?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Local\Continuum\anaconda3\lib\site-packages\minecart\miner.py", line 350, in get_page
    self.interpreter.process_page(page)
  File "C:\Users\Local\Continuum\anaconda3\lib\site-packages\pdfminer\pdfinterp.py", line 642, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "C:\Users\Local\Continuum\anaconda3\lib\site-packages\pdfminer\pdfinterp.py", line 652, in render_contents
    self.execute(list_value(streams))
  File "C:\Users\Local\Continuum\anaconda3\lib\site-packages\pdfminer\pdfinterp.py", line 675, in execute
    func(*args)
  File "C:\Users\Local\Continuum\anaconda3\lib\site-packages\pdfminer\pdfinterp.py", line 435, in do_CS
    self.scs = self.csmap[literal_name(name)]
KeyError: 'R13'

**Comment by felipeochoa** [comment]
Which pdfminer are you using? (There are a couple of Python 3 forks floating around)

**Comment by himansu979** [comment]
I am using python 3.6.2 through Anaconda, 
pdfminer.__version__
'20170720'

**Comment by felipeochoa** [comment]
Can you make sure you've installed pdfminer3k? You might be using the one for Python 2 here, so it could be a bytes vs str issue.

**Comment by himansu979** [comment]
Hi, Thank you for the response. I reinstalled again pdfminer3k through pip. 
Below is output from conda list.
pdfminer3k                1.3.1                     <pip>
with version 1.3.1, I don't see the above issue.

in some pdf files, page.letterings is breaking the words. Below is the example, I am trying to check the word "Property Address"
file 1, output is correct
<Lettering: Property Address (27.78800000000001, 948.5960000000003, 78.46800000000002, 959.7400000000004)>

file 2, it is read as multiple words.
[<Lettering: P (87.40453403817241, 745.3251727698116, 90.84281603285906, 751.5543088881561)>,
 <Lettering: roperty (90.84358507659853, 745.3251727698116, 106.88471058014575, 751.5543088881561)>,
 <Lettering:   (106.88375110461232, 745.3251727698116, 108.31689241135557, 751.5543088881561)>,
 <Lettering: A (108.31382356553263, 745.3251727698116, 111.75210556021928, 751.5543088881561)>,
 <Lettering: ddres (111.75593612693245, 745.3251727698116, 124.64792218013596, 751.5543088881561)>,
 <Lettering: s (124.64697003373743, 745.3251727698116, 127.22411010288099, 751.5543088881561)>]

Do I need to set any parameters to read it as a single word?

Thanks.

**Comment by felipeochoa** [comment]
Unfortunately that is based on how the PDF was created. Sometimes they have the equivalent of `render_string('Property Address', x, y)` and sometimes they have `render_string('P', x1, y1); render_string('r', x2, y2)` ... etc. When it's the former, pdfminer picks it up in its entirety. When it's the latter you unfortunately get the multiple words.

Pdfminer does have a rudimentary layout analyzer, but for my purposes I always found it easier to do some ad-hoc merging. Of course, it depends on the regularity of your PDFs, your goals etc. which approach you take

**Comment by himansu979** [comment]
Hi, thank you for explaining this. 
Here is the sample PDF file I am trying to read : 
https://www.appraisalservice-sac.com/documents/appraisal_report.pdf

from page4, I am trying to extract the following field.
Property Address = 4816 Village Sample Drive
City = EI Dorado Hills
state = CA
Zip Code = 95762

when minecart extracts the entire word, it is easier to search using the bbox close to it to extract the address value. but some of pdfs, I get partial words and single letters. Any suggestion how to use this to extract the values?
Thanks a lot.

**Comment by felipeochoa** [comment]
If the reports are all in the same format, you could determine a reasonable bounding box to use and hard-code that into your script. Then using the `iter_in_bbox` method you could collect all the `Lettering` objects in use, sort them based on x coordinate and join them.

**Comment by himansu979** [comment]
Thanks for the suggestion. I will check this method.
