### ISSUE TITLE
PDF miner compatibility may be

### ISSUE THREAD

**Issue by totopopov** [felipeochoa/minecart#17]
When parsing a pdf, with:
`doc = minecart.Document(pdf_file)`
results in an error _AttributeError: module 'pdfminer.pdfparser' has no attribute 'PDFDocument'_

**Comment by felipeochoa** [comment]
Are you using `pdfminer3k`?

**Comment by totopopov** [comment]
I think so, v 1.3.1

**Comment by felipeochoa** [comment]
What's the output of `pip list`?

**Comment by felipeochoa** [comment]
See #13

**Comment by totopopov** [comment]
Well, problem was indeed `pdfminer.six`. Thanks for the fast and correct response.
