### ISSUE TITLE
pdfminer.pdffont.PDFUnicodeNotDefined: key 127

### ISSUE THREAD

**Issue by MarioCamunda** [felipeochoa/minecart#25]
I use this code to get the content of a page of a PDF using minecart:

`pdf = open(pdffile.name, 'rb')`
`doc = minecart.Document(pdf)`
`page = doc.get_page(0)`

It generally works. But this error occurs, when there is a bullet point (U+2022) in the PDF:

`.../pdffont.py", line 520, in to_unichr`
    `raise PDFUnicodeNotDefined(None, cid)`
`pdfminer.pdffont.PDFUnicodeNotDefined: (None, 127)`

This error occurs in class PDFSimpleFont in function to_unichr, because key 127 is not in list self.cid2unicode.

Following questions:

1) Do you know that issue? Will you fix it?

2) I tried to overwrite function to_unichr in class PDFSimpleFont and suppress the error. For example like this:

`oldSimpleFont=pdfminer.pdffont.PDFSimpleFont`
`class MyPDFSimpleFont(oldSimpleFont):`
    `def __init__(self, descriptor, widths, spec):`
        `oldSimpleFont.__init__(self, descriptor, widths, spec)`

     def to_unichr(self, cid):
         if self.unicode_map:
             try:
                 return self.unicode_map.get_unichr(cid)
             except KeyError:
                 pass
          try:
             return self.cid2unicode[cid]
          except KeyError:
             pass
`pdfminer.pdffont.PDFSimpleFont = MyPDFSimpleFont`

But it does not work. Can you give a hint, how to do it best?

3) Or do you have another suggestion to solve the problem? For example, to get the missing key in the list?

4) Do you need some more information?

Note: the indentations in the code have unfortunately not been adopted correctly

**Comment by felipeochoa** [comment]
This could be a bug in pdfminer, or it could be that your PDF is corrupted and doesn't include glyph information for BULLET. You could try checking on pdfminer to diagnose
