### ISSUE TITLE
How I can identify Flowchart(shapes) using minecart?

### ISSUE THREAD

**Issue by Arun2985** [felipeochoa/minecart#26]
I am using [minecart][1] library for reading pdf file. I am able to get the cords of the shapes but i am unable to identify the shape. please help me .
actually I am doing to identify flowchart from pdf so am research upon it. Flowchart has made by shapes can i find shapes from pdf?

**Comment by DEKKAR-AHMED** [comment]
i think we have the same probleme

**Comment by DEKKAR-AHMED** [comment]
did you resolve the probleme ????????????

**Comment by felipeochoa** [comment]
This is separate functionality from minecart. Sounds like you need some kind of computer vision algorithm, since PDF only indicates shape coordinates, not any semantic info
