### ISSUE TITLE
get_bbox in your content.py

### ISSUE THREAD

**Issue by DEKKAR-AHMED** [felipeochoa/minecart#28]
i try to use you function to extract the position of graph in pdf  document. the function returns me the correct ansert you  the cordinate of x axis but not for the y axis .
i tried to understand how your function works but i m a little lost.
can i have your inttention please and you help

**Comment by felipeochoa** [comment]
> To keep things simple, minecart defines its own coordinate
> system in which all metrics are expressed. This coordinate system has as its
> origin the bottom-left corner of the page, and has the positive x axis
> extending to the right and the positive y axis to the top. A unit on these
> axes corresponds to 1/72 of an inch.
