### ISSUE TITLE
'GraphicsCollection' object has no attribute 'font'

### ISSUE THREAD

**Issue by ShriShalini** [felipeochoa/minecart#29]
I am trying to extract the font of a text in a pdf. Following is the piece of the code where I try to do the same.
letterings_font = page.letterings.font

But I keep getting the error 'GraphicsCollection' object has no attribute 'font'. 
The documentation says that I can access the font from the letterings object.
 Any help would be appreciated.

**Comment by felipeochoa** [comment]
letterings is a collection, not an individual lettering. You probably want to iterate through the page.letterings object
