### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shapes'

### ISSUE THREAD

**Issue by Pavan-Kumar122** [felipeochoa/minecart#30]
Done Everything for resolving this , but it didn't solved.
it gives me new error whenever i tried to change.
/* code ..

import minecart
pdffile = open('sample.pdf', 'rb')
doc = minecart.Document(pdffile)
page = doc.get_page(3)
for shape in page.shapes.iter_in_bbox((0, 0, 100, 200)):
    print (shape.path, shape.fill.color.as_rgb())
im = page.images[0].as_pil()  # requires pillow
im.show()

*/

**Comment by felipeochoa** [comment]
`page` is `None`, which indicates the PDF doesn't have a 4th page
