### ISSUE TITLE
module 'pdfminer.pdfparser' has no attribute 'PDFDocument'

### ISSUE THREAD

**Issue by bjornasm** [felipeochoa/minecart#31]
I've tried following the solution presented in the other issues (removing pdfminer.six etc) but the problem still prevails. For some reason these issues stands as closed without any reasonalbe indication that this problem is resolved.

Edit: Uninstalling minecart, pypdf2, pdfminer.six and pdfminer3k and reloading the kernel of my jupyter notebook did the trick. Can we get an explisit warning against installing pdfminer.six in the docs?

**Comment by felipeochoa** [comment]
Sure, PR welcome
