### ISSUE TITLE
AttributeError: 'PDFGraphicState' object has no attribute 'stroke_color'

### ISSUE THREAD

**Issue by babahadjsaid** [felipeochoa/minecart#32]
hi i'm trying to extract figures and images from a pdf but i'm getting this error hope someone can help me 

>   AttributeError                            Traceback (most recent call last)
    <ipython-input-44-33512d72686c> in <module>
          3 doc = minecart.Document(pdffile)
          4 for i in range(21):
    ----> 5     page = doc.get_page(i)
          6     try:
          7         for shape in page.shapes.iter_in_bbox((0, 0, 100, 200)):

    ~/.conda/envs/chatbot/lib/python3.6/site-packages/minecart/miner.py in get_page(self, num)
        348         for i, page in enumerate(self.doc.get_pages()):
        349             if i == num:
    --> 350                 self.interpreter.process_page(page)
        351                 return self.device.page

    ~/.conda/envs/chatbot/lib/python3.6/site-packages/pdfminer/pdfinterp.py in process_page(self, page)
        640             ctm = (1,0,0,1, -x0,-y0)
        641         self.device.begin_page(page, ctm)
    --> 642         self.render_contents(page.resources, page.contents, ctm=ctm)
        643         self.device.end_page(page)
        644 

    ~/.conda/envs/chatbot/lib/python3.6/site-packages/pdfminer/pdfinterp.py in render_contents(self, resources, streams, ctm)
        650         self.init_resources(resources)
        651         self.init_state(ctm)
    --> 652         self.execute(list_value(streams))
        653 
        654     def execute(self, streams):

    ~/.conda/envs/chatbot/lib/python3.6/site-packages/pdfminer/pdfinterp.py in execute(self, streams)
        673                         # logger.debug('exec: %s %r', name, args)
        674                         if len(args) == nargs:
    --> 675                             func(*args)
        676                     else:
        677                         # logger.debug('exec: %s', name)

    ~/.conda/envs/chatbot/lib/python3.6/site-packages/pdfminer/pdfinterp.py in do_Do(self, xobjid)
        618             resources = dict_value(xobj.get('Resources')) or self.resources.copy()
        619             self.device.begin_figure(xobjid, bbox, matrix)
    --> 620             interpreter.render_contents(resources, [xobj], ctm=mult_matrix(matrix, self.ctm))
        621             self.device.end_figure(xobjid)
        622         elif subtype is LITERAL_IMAGE and 'Width' in xobj and 'Height' in xobj:

    ~/.conda/envs/chatbot/lib/python3.6/site-packages/pdfminer/pdfinterp.py in render_contents(self, resources, streams, ctm)
        650         self.init_resources(resources)
        651         self.init_state(ctm)
    --> 652         self.execute(list_value(streams))
        653 
        654     def execute(self, streams):

    ~/.conda/envs/chatbot/lib/python3.6/site-packages/pdfminer/pdfinterp.py in execute(self, streams)
        676                     else:
        677                         # logger.debug('exec: %s', name)
    --> 678                         func()
        679                 else:
        680                     handle_error(PDFInterpreterError, 'Unknown operator: %r' % name)

    ~/.conda/envs/chatbot/lib/python3.6/site-packages/pdfminer/pdfinterp.py in do_S(self)
        389     # stroke
        390     def do_S(self):
    --> 391         self.device.paint_path(self.graphicstate, True, False, False, self.curpath)
        392         self.curpath = []
        393     # close-and-stroke

    ~/.conda/envs/chatbot/lib/python3.6/site-packages/minecart/miner.py in paint_path(self, graphicstate, stroked, filled, evenodd, path)
        243                                                               (x, y)))
        244             device_path.append(tuple(new_seg))
    --> 245         stroke = StrokeState.from_gs(graphicstate) if stroked else None
        246         fill = FillState.from_gs(graphicstate) if filled else None
        247         self.page.add_shape(Shape(stroke, fill, evenodd, device_path))

    ~/.conda/envs/chatbot/lib/python3.6/site-packages/minecart/miner.py in from_gs(cls, graphics)
         60         "Creates a new StrokeState from a ColoredState object."
         61         ret = cls()
    ---> 62         ret.color = graphics.stroke_color
         63         ret.linewidth = graphics.linewidth
         64         ret.linecap = graphics.linecap

    AttributeError: 'PDFGraphicState' object has no attribute 'stroke_color'

**Comment by felipeochoa** [comment]
For some reason the interpreter is not using `ColoredState` for its graphics state but rather the one built into pdfminer. Are you using `pdfminer3k`?
