### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kmanojkkmr** [felipeochoa/minecart#34]
When I am trying to install, I am getting the below error.

(table_detection) C:\Users\manoj.kadamalakaluva\Project\PDF-Table-Structure-Reco
gnition-using-deep-learning\tablegenerator>pip install minecart
Collecting minecart
  Using cached minecart-0.3.0-py3-none-any.whl (23 kB)
ERROR: Could not find a version that satisfies the requirement pdfminer3k (from
minecart) (from versions: none)
ERROR: No matching distribution found for pdfminer3k (from minecart)

I don't see pdfminer3k for installation. Could you please suggest me any alternative for this.

Thank you in advance.

**Comment by felipeochoa** [comment]
Sounds like an issue with your pip version or local environment. I just tried a clean install and it worked correctly
