### ISSUE TITLE
Minecart Shapes Documentation

### ISSUE THREAD

**Issue by rahulg-infiswift** [felipeochoa/minecart#36]
@felipeochoa I have extracted page.shape.path but I am not able to locate the documentation for minecart.Shape. What are the meaning of m, l and h in this list? [('m', 11277.879, 1218.329), ('l', 9908.092, 1218.329), ('l', 9908.092, 1261.136)]?

**Comment by felipeochoa** [comment]
Those are [path commands](https://en.wikipedia.org/wiki/PDF#Vector_graphics). It's part of [the PDF spec](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf), so you can look through that or look at [online tutorials]( https://blog.idrsolutions.com/2010/11/grow-your-own-pdf-file-%E2%80%93-part-5-path-objects/). The spec is quite approachable -- section 4.4 is what you need.

It's similar to SVG paths, which [MDN has documented](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#Path_commands)

The only minecart specific feature here is that the path coordinates are all normalized to the page axes.
