### ISSUE TITLE
'_bbox': None

### ISSUE THREAD

**Issue by KartikGupta0421** [felipeochoa/minecart#40]
I am trying to annotate pdf words with the help of sample code provided in example.  The value of __bbox is reflecting as none while traversing in the for loop. Please find the attached PDF and screenshot 
[011.pdf](https://github.com/felipeochoa/minecart/files/6151505/011.pdf)

![image](https://user-images.githubusercontent.com/78254452/111362747-2e5d4880-86b5-11eb-9ccd-98a229890f8b.png)

**Comment by felipeochoa** [comment]
The leading underscore indicates it's a private attribute. You should use `.get_bbox()` which is public and in charge of initializing bounding boxes for curves
