### ISSUE TITLE
AttributeError: module 'pdfminer.pdfparser' has no attribute 'PDFDocument'

### ISSUE THREAD

**Issue by gitsnehasish** [felipeochoa/minecart#41]
import minecart
pdffile = open('example.pdf', 'rb')
doc = minecart.Document(pdffile)

The above command not working. Getting the Below error.

AttributeError: module 'pdfminer.pdfparser' has no attribute 'PDFDocument'

**Comment by felipeochoa** [comment]
#20 #31
